# Generated by Django 5.2.11 on 2026-02-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FINANCIAL', 'Financial Risk'), ('PRIVACY', 'Privacy Risk'), ('LEGAL', 'Legal Risk'), ('SUBSCRIPTION', 'Subscription Risk')], max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('clause_text', models.TextField()),
                ('explanation', models.TextField()),
                ('page_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analyses', to='documents.document')),
            ],
            options={
                'ordering': ['-risk_level', '-created_at'],
            },
        ),
    ]
